import { useEffect, useRef, useState } from 'react';
import socket from './socket';
import { SyncEngine } from './sync';
import { WebRTCManager } from './webrtc';
import styles from './App.module.css';

export default function App() {
  const videoRef = useRef(null), syncRef = useRef(null), rtcRef = useRef(null), urlRef = useRef(''), roomRef = useRef(''), hostRef = useRef(false), hbRef = useRef(0), viewerInitRef = useRef(false), hostInitRef = useRef(false);
  const [username, setUsername] = useState(''), [joinRoomId, setJoinRoomId] = useState(''), [roomId, setRoomId] = useState(''), [isHost, setIsHost] = useState(false), [joined, setJoined] = useState(false), [members, setMembers] = useState([]), [messages, setMessages] = useState([]), [message, setMessage] = useState(''), [syncText, setSyncText] = useState('In sync'), [hostLoaded, setHostLoaded] = useState(false), [hostLeft, setHostLeft] = useState(false), [videoSrc, setVideoSrc] = useState(''), [me, setMe] = useState(socket.id || ''), [copied, setCopied] = useState(false), [error, setError] = useState(''), [streamConnected, setStreamConnected] = useState(false), [manualFallback, setManualFallback] = useState(false), [viewerCount, setViewerCount] = useState(0), [debugOpen, setDebugOpen] = useState(false), [debugPeers, setDebugPeers] = useState([]), [debugStats, setDebugStats] = useState([]);

  useEffect(() => { roomRef.current = roomId; hostRef.current = isHost; }, [roomId, isHost]);
  useEffect(() => { const key = e => { if (e.ctrlKey && e.shiftKey && e.key.toLowerCase() === 'd') { e.preventDefault(); setDebugOpen(v => !v); } }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key); }, []);

  useEffect(() => {
    const onConnect = () => setMe(socket.id || '');
    socket.on('connect', onConnect);
    socket.on('room-joined', d => { setRoomId(d.roomId); setMembers(d.members || []); setJoined(true); setIsHost(d.hostId === socket.id); setHostLoaded(!!d.streamReady); setHostLeft(false); });
    socket.on('user-joined', d => d.members && setMembers(d.members));
    socket.on('user-left', d => setMembers(list => list.filter(u => u.socketId !== d.socketId)));
    socket.on('host-left', () => { setHostLeft(true); setHostLoaded(false); setStreamConnected(false); rtcRef.current?.closeAll(); viewerInitRef.current = false; });
    socket.on('host-changed', d => { setHostLeft(true); setMembers(d.members || []); setIsHost(d.hostId === socket.id); setHostLoaded(false); setStreamConnected(false); viewerInitRef.current = false; hostInitRef.current = false; rtcRef.current?.closeAll(); });
    socket.on('host-loaded-video', () => setHostLoaded(true));
    socket.on('host-stream-ready', d => { if (d.roomId === roomRef.current) { setHostLoaded(true); setStreamConnected(false); viewerInitRef.current = false; } });
    socket.on('heartbeat', d => { if (d.roomId === roomRef.current && !hostRef.current) hbRef.current = d.time; });
    socket.on('chat', d => setMessages(list => [...list, d]));
    socket.on('disconnect', () => setSyncText('Disconnected'));
    return () => { socket.off('connect', onConnect); socket.off('room-joined'); socket.off('user-joined'); socket.off('user-left'); socket.off('host-left'); socket.off('host-changed'); socket.off('host-loaded-video'); socket.off('host-stream-ready'); socket.off('heartbeat'); socket.off('chat'); socket.off('disconnect'); };
  }, []);

  useEffect(() => { if (!joined || !roomId || !videoRef.current) return; syncRef.current?.destroy(); syncRef.current = new SyncEngine(socket, videoRef.current, isHost, setSyncText); syncRef.current.attach(roomId); return () => syncRef.current?.destroy(); }, [joined, roomId, isHost]);
  useEffect(() => { if (!joined) return; rtcRef.current?.closeAll(); rtcRef.current = new WebRTCManager(socket, isHost, { onPeerCountChange: setViewerCount, onStreamReceived: () => { setStreamConnected(true); setManualFallback(false); }, onUnsupported: msg => { setError(msg); if (!isHost) setManualFallback(true); }, onConnectionFailed: msg => { setError(msg); setManualFallback(true); setStreamConnected(false); viewerInitRef.current = false; videoRef.current && (videoRef.current.srcObject = null); } }); rtcRef.current.setRoomId(roomId); viewerInitRef.current = false; hostInitRef.current = false; return () => rtcRef.current?.closeAll(); }, [joined, roomId, isHost]);
  useEffect(() => { if (debugOpen && rtcRef.current) { const t = setInterval(async () => { setDebugPeers(rtcRef.current.getDebugState()); setDebugStats(await rtcRef.current.collectStats()); }, 2000); return () => clearInterval(t); } }, [debugOpen, joined]);
  useEffect(() => { if (!joined || isHost || !hostLoaded || manualFallback || streamConnected || viewerInitRef.current || !videoRef.current) return; viewerInitRef.current = true; rtcRef.current?.initViewer(videoRef.current, roomId); }, [joined, isHost, hostLoaded, manualFallback, streamConnected, roomId]);
  useEffect(() => { if (joined && isHost && videoSrc && videoRef.current && !hostInitRef.current && videoRef.current.readyState >= 1) { hostInitRef.current = !!rtcRef.current?.initHost(videoRef.current, roomId); } }, [joined, isHost, videoSrc, roomId]);
  useEffect(() => () => { if (urlRef.current) URL.revokeObjectURL(urlRef.current); }, []);

  const startRoom = type => { setError(''); const payload = { username: username.trim() || 'Guest' }, joinPayload = { roomId: joinRoomId.trim().toUpperCase(), username: payload.username }; socket.emit(type, type === 'create-room' ? payload : joinPayload, res => { if (!res?.ok) return setError(res?.error || 'Unable to join room'); setRoomId(res.roomId); setMembers(res.members || []); setJoined(true); setIsHost(type === 'create-room'); setHostLoaded(!!res.streamReady); setManualFallback(false); setStreamConnected(false); }); };
  const onFile = e => { const file = e.target.files?.[0]; if (!file || !videoRef.current) return; if (urlRef.current) URL.revokeObjectURL(urlRef.current); const url = URL.createObjectURL(file); urlRef.current = url; setVideoSrc(url); setStreamConnected(false); setManualFallback(false); setHostLoaded(false); hostInitRef.current = false; viewerInitRef.current = false; videoRef.current.srcObject = null; videoRef.current.onloadedmetadata = () => { if (rtcRef.current?.initHost(videoRef.current, roomRef.current)) hostInitRef.current = true; }; };
  const sendMessage = () => { const text = message.trim(); if (!text || !roomId) return; socket.emit('chat', { roomId, message: text, username: username.trim() || 'Guest' }); setMessage(''); };
  const copyRoom = async () => { await navigator.clipboard.writeText(roomId); setCopied(true); setTimeout(() => setCopied(false), 1000); };
  const streamText = isHost ? `Streaming to ${viewerCount} viewers` : streamConnected ? 'Stream connected ✓' : hostLoaded ? 'Connecting to host stream...' : 'Waiting for host to load video...';
  const drift = hostRef.current ? 0 : Math.abs((videoRef.current?.currentTime || 0) - (hbRef.current || 0)).toFixed(2);

  if (!joined) return <div className={styles.shell}><div className={styles.card}><h1>Watch Together</h1><p>Phase 1 sync engine. Load the same local file on every device and let the host drive playback.</p><input placeholder="Username" value={username} onChange={e => setUsername(e.target.value)} /><div className={styles.row}><button onClick={() => startRoom('create-room')}>Create Room</button><input placeholder="Room ID" value={joinRoomId} onChange={e => setJoinRoomId(e.target.value)} /><button onClick={() => startRoom('join-room')}>Join Room</button></div>{error && <p className={styles.error}>{error}</p>}</div></div>;

  return <div className={styles.shell}><header className={styles.topbar}><div><h1>Room {roomId}</h1><p>{streamText}</p></div><div className={styles.meta}><span>{syncText}</span><span className={styles.badge}>Drift {drift}s</span><button onClick={copyRoom}>{copied ? 'Copied' : 'Copy room'}</button></div></header>{hostLeft && <div className={styles.banner}>Host left the room. Waiting for reassignment.</div>}{error && <div className={styles.banner}>{error}</div>}<main className={styles.grid}><section className={styles.videoPanel}>{(isHost || manualFallback) && <input type="file" accept="video/*" onChange={onFile} />}<div className={styles.videoWrap}><video ref={videoRef} src={(isHost || manualFallback) && videoSrc ? videoSrc : undefined} controls={isHost || manualFallback} autoPlay playsInline muted={false} className={styles.video} style={{ pointerEvents: isHost || manualFallback ? 'auto' : 'none' }} /></div>{!videoSrc && (isHost ? <p className={styles.hint}>Load your local file here.</p> : manualFallback ? <p className={styles.hint}>Direct streaming not supported on this browser. Please load the video file manually.</p> : <p className={styles.hint}>{streamConnected ? 'Stream connected ✓' : hostLoaded ? 'Connecting to host stream...' : 'Waiting for host to load video...'}</p>)}</section><aside className={styles.side}><section className={styles.card}><h2>People</h2><ul>{members.map(u => <li key={u.socketId}>{u.username}{u.socketId === me ? ' (you)' : ''}{u.isHost ? ' · host' : ''}</li>)}</ul></section><section className={styles.card}><h2>Chat</h2><div className={styles.chat}>{messages.map((m, i) => <div key={i}><strong>{m.username || 'Guest'}:</strong> {m.message}</div>)}</div><div className={styles.row}><input value={message} onChange={e => setMessage(e.target.value)} onKeyDown={e => e.key === 'Enter' && sendMessage()} placeholder="Send a message" /><button onClick={sendMessage}>Send</button></div></section></aside></main>{debugOpen && <section className={styles.debugPanel}><h2>Debug</h2><div>Peers: {debugPeers.length}</div><div>{debugStats.map(p => <div key={p.id}>{p.id}: {p.state} sent {p.bytesSent} recv {p.bytesReceived}</div>)}</div></section>}</div>;
}
